name: Check sources
on: push
jobs:
  myScript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check script
        run: test -e run.sh
      - name: testRun
        run: make test      
  shellcheck:
    name: ShellMeli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
