name: Check sources
on: 
  push:
    branches-ignore: 
      main
jobs:
  myScript:
    runs-on: ubuntu-latest    
    needs: shellcheck
    steps:
      - uses: actions/checkout@v2
      - name: Check script
        run: test -e run.sh        
  shellcheck:
    name: ShellMeli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        
  runtests:
    needs: shellcheck
    name: RunTests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: make tests
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 
            ghcr.io/${{ github.repository }}:latest,
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
  
#  documentaiton:
#   runs-on: ubuntu-latest
#   steps:
#      - uses: actions/checkout@v2
#      - run: make doc
#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v4
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./dist
      
