name: Check sources
on: push
jobs:
  myScript:
    runs-on: ubuntu-latest    
    needs: shellcheck
    steps:
      - uses: actions/checkout@v2
      - name: Check script
        run: test -e run.sh        
  shellcheck:
    name: ShellMeli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        
  runtests:
    needs: shellcheck
    name: RunTests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: make tests
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/container
        with:
          docker_repo: trialk033s3.jfrog.io/docker-trial
          docker_user: melissa
          docker_token: ${{ secrets.JFROG_DOCKER_TOKEN }}

  sonarqube:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4 # Ex: v4.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ vars.SONAR_TOKEN  }}
    

  
#  documentaiton:
#   runs-on: ubuntu-latest
#   steps:
#      - uses: actions/checkout@v2
#      - run: make doc
#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v4
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./dist
      
